#!/usr/bin/env python3
"""Extract answer keys from every readiness pool into a seed file for Supabase.

The score-integrity design keeps correct answers + explanations OUT of the
student's reach by grading server-side. This script reads each lesson's
`data-kind="readiness"` pool and emits INSERT statements for public.question_keys
(check_id, question_id, correct_index, explain).

The answer keys are NOT stored in this (public, student-forked) repo — they are
written into the private `au-cohort-tracker` repo so they never ship in a student
fork. This script reads the lesson pools here and writes the seed there.

Usage:
    # writes ../au-cohort-tracker/supabase/seed/question_keys.sql (sibling checkout)
    python scripts/build_readiness_keys.py
    # point at a specific au-cohort-tracker checkout:
    AU_COHORT_TRACKER=/path/to/au-cohort-tracker python scripts/build_readiness_keys.py
    # --json also writes question_keys.json alongside the .sql
    python scripts/build_readiness_keys.py --json

Run after any edit to a readiness pool, then re-seed (see the au-cohort-tracker
repo's supabase/README.md).
"""
from __future__ import annotations
import glob, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def cohort_tracker_root() -> str:
    """Locate the private au-cohort-tracker checkout that receives the keys.

    Order: $AU_COHORT_TRACKER, else a sibling `au-cohort-tracker/` next to this repo.
    """
    env = os.environ.get("AU_COHORT_TRACKER")
    if env:
        return os.path.abspath(os.path.expanduser(env))
    return os.path.abspath(os.path.join(ROOT, os.pardir, "au-cohort-tracker"))
# Seed keys for every server-persisted check: readiness pools + end-of-lesson
# self-checks (wrap-up in lesson index.md) + weekly knowledge-checks (wrap-up,
# data-id "*-canonical", in knowledge-check.md). All are data-kind readiness/wrap-up.
POOL_RE = re.compile(
    r'<div class="ox-self-check"[^>]*data-kind="(?:readiness|wrap-up)"[^>]*>\s*'
    r'<script[^>]*class="ox-self-check__pool">(.*?)</script>',
    re.S,
)
ID_RE = re.compile(r'data-id="([^"]+)"')


def sql_str(s: str) -> str:
    return "'" + (s or "").replace("'", "''") + "'"


def main() -> int:
    rows = []
    sources = (glob.glob(os.path.join(ROOT, "docs/lessons/week-*/module-*/index.md"))
               + glob.glob(os.path.join(ROOT, "docs/lessons/week-*/module-*/knowledge-check.md")))
    for f in sorted(sources):
        text = open(f, encoding="utf-8").read()
        for m in POOL_RE.finditer(text):
            div = text[m.start(): m.start() + 400]
            did = ID_RE.search(div)
            if not did:
                continue
            check_id = did.group(1)
            try:
                pool = json.loads(m.group(1).strip())
            except json.JSONDecodeError as e:
                print(f"!! {check_id}: bad JSON ({e})", file=sys.stderr)
                return 1
            for qid, q in enumerate(pool):
                rows.append((check_id, qid, int(q["answer"]), q.get("explain", "")))

    cohort_root = cohort_tracker_root()
    if not os.path.isdir(cohort_root):
        print(f"!! au-cohort-tracker checkout not found at {cohort_root}\n"
              f"   Clone it as a sibling of this repo, or set AU_COHORT_TRACKER "
              f"to its path. Answer keys are written there (never into this "
              f"public repo).", file=sys.stderr)
        return 1
    out_dir = os.path.join(cohort_root, "supabase", "seed")
    os.makedirs(out_dir, exist_ok=True)
    sql_path = os.path.join(out_dir, "question_keys.sql")
    with open(sql_path, "w", encoding="utf-8") as fh:
        fh.write("-- AUTO-GENERATED by scripts/build_readiness_keys.py — do not edit by hand.\n")
        fh.write("truncate table public.question_keys;\n")
        fh.write("insert into public.question_keys (check_id, question_id, correct_index, explain) values\n")
        fh.write(",\n".join(
            f"  ({sql_str(c)}, {qid}, {ci}, {sql_str(ex)})" for c, qid, ci, ex in rows
        ))
        fh.write("\non conflict (check_id, question_id) do update set\n"
                 "  correct_index = excluded.correct_index, explain = excluded.explain;\n")
    print(f"Wrote {len(rows)} keys across "
          f"{len({r[0] for r in rows})} checks -> {os.path.relpath(sql_path, ROOT)}")

    if "--json" in sys.argv:
        json_path = os.path.join(out_dir, "question_keys.json")
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump([
                {"check_id": c, "question_id": q, "correct_index": ci, "explain": ex}
                for c, q, ci, ex in rows
            ], fh, indent=2)
        print(f"Wrote {os.path.relpath(json_path, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
