#!/usr/bin/env python3
"""Extract answer keys from every readiness pool into a seed file for Supabase.

The score-integrity design keeps correct answers + explanations OUT of the
student's reach by grading server-side. This script reads each lesson's
`data-kind="readiness"` pool and emits INSERT statements for public.question_keys
(check_id, question_id, correct_index, explain).

Usage:
    python scripts/build_readiness_keys.py        # writes supabase/seed/question_keys.sql
    python scripts/build_readiness_keys.py --json  # also writes question_keys.json

Run after any edit to a readiness pool, then re-seed (see supabase/README.md).
"""
from __future__ import annotations
import glob, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Seed keys for BOTH readiness pools and end-of-lesson self-checks (wrap-up in
# lesson index.md). Canonical weekly knowledge-checks live in knowledge-check.md,
# which this glob does not read, so they are excluded automatically.
POOL_RE = re.compile(
    r'<div class="ox-self-check"[^>]*data-kind="(?:readiness|wrap-up)"[^>]*>\s*'
    r'<script[^>]*class="ox-self-check__pool">(.*?)</script>',
    re.S,
)
ID_RE = re.compile(r'data-id="([^"]+)"')


def sql_str(s: str) -> str:
    return "'" + (s or "").replace("'", "''") + "'"


def main() -> int:
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "docs/lessons/week-*/module-*/index.md"))):
        text = open(f, encoding="utf-8").read()
        for m in POOL_RE.finditer(text):
            div = text[m.start(): m.start() + 400]
            did = ID_RE.search(div)
            if not did:
                continue
            check_id = did.group(1)
            try:
                pool = json.loads(m.group(1).strip())
            except json.JSONDecodeError as e:
                print(f"!! {check_id}: bad JSON ({e})", file=sys.stderr)
                return 1
            for qid, q in enumerate(pool):
                rows.append((check_id, qid, int(q["answer"]), q.get("explain", "")))

    out_dir = os.path.join(ROOT, "supabase", "seed")
    os.makedirs(out_dir, exist_ok=True)
    sql_path = os.path.join(out_dir, "question_keys.sql")
    with open(sql_path, "w", encoding="utf-8") as fh:
        fh.write("-- AUTO-GENERATED by scripts/build_readiness_keys.py — do not edit by hand.\n")
        fh.write("truncate table public.question_keys;\n")
        fh.write("insert into public.question_keys (check_id, question_id, correct_index, explain) values\n")
        fh.write(",\n".join(
            f"  ({sql_str(c)}, {qid}, {ci}, {sql_str(ex)})" for c, qid, ci, ex in rows
        ))
        fh.write("\non conflict (check_id, question_id) do update set\n"
                 "  correct_index = excluded.correct_index, explain = excluded.explain;\n")
    print(f"Wrote {len(rows)} keys across "
          f"{len({r[0] for r in rows})} checks -> {os.path.relpath(sql_path, ROOT)}")

    if "--json" in sys.argv:
        json_path = os.path.join(out_dir, "question_keys.json")
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump([
                {"check_id": c, "question_id": q, "correct_index": ci, "explain": ex}
                for c, q, ci, ex in rows
            ], fh, indent=2)
        print(f"Wrote {os.path.relpath(json_path, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
